### ISSUE TITLE
Trouble to reboot directories

### ISSUE THREAD

**Issue by aurrelhebert** [senx/warp10-platform#890] opened 2020-12-16 10:22 UTC
We have Warp10 version 2.5 deployed directories (sharded and replicated). They load around 130 millions of series. I noticed that we do get trouble to restart them while series deletion is occuring. In the logs, we got:
pool-301-thread-29 ERROR store.Directory - 
java.lang.InterruptedException
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
  at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:63)
  at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:33)
  at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:66)
  at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:58)
  at io.warp10.continuum.store.Directory$DirectoryConsumer.run(Directory.java:1459)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)

And in terms of Metrics it's related to a lot of "warp.directory.kafka.shutdowns". 

The rebooted directory do not consume Kafka. 

Our workaround at the moment is to forbid deletes while rebooting directories.

Let me know if this issue was already fix in new Warp10 version

**Comment by hbs** [comment] 2020-12-16 10:45
How many CPU/cores/threads does the machine running your Directories have?

**Comment by aurrelhebert** [comment] 2020-12-16 11:13
56 cores for 32 threads

**Comment by hbs** [comment] 2020-12-16 13:41
Do you see any Kafka or HBase related messages in the logs? The stack trace you provided is a consequence of an abort which can be triggered by either a Kafka or an HBase issue.

**Comment by hbs** [comment] 2020-12-16 13:48
Also check the following metrics:

warp.directory.hbase.puts
warp.directory.hbase.deletes
warp.directory.hbase.commits
warp.directory.barrier.syncs
warp.directory.kafka.commits

around the time where you experience the issue

**Comment by aurrelhebert** [comment] 2020-12-16 14:23
I do not get any other errors, Kafka and HBase are fine, all other directories in the same partition are fine (however on the failed reboot, they was some meta delete recorded by other directories of the same partition when no delete when a reboot is working).
All those five Metrics are or not recorded, or at zero for the failing directory.

**Comment by hbs** [comment] 2020-12-16 21:22
The kafka shutdowns count increases when the consumption loop is aborted, and these aborts have two causes, either an error while reading from or committing offsets to Kafka, or an error while processing a batch of HBase mutations, so either one of those must be happening.

I strongly suggest you try 2.7.1 for one of your Directory as you will get some additional metrics exposed, i.e. the ones I asked you to check above. This should help diagnose further the issue, but it does not seem to be caused by a bug in the Directory, more by an operational situation affecting HBase or less likely Kafka.

Note also that the consumption off of Kafka only starts once the Directory has loaded its Geo Time Series from HBase, so technically the Directory has booted before the metadata topic is started to be consumed.

**Comment by aurrelhebert** [comment] 2020-12-17 10:25
For information, all our directory are up and running. To make a reboot successful, I simply **deactivate** **deletion** on ingress side while a directory starts. The operational situation was OK on HBASE (everything ok, read and put ok) or on Kafka side (consume ok). A "failing directory" was able to read HBase, do its GC and consume a very few message on Kafka before getting stuck with this error. As it's not a transparent operation, I will avoid to reproduce it on our production.
From the test I run, starting a directory **without** HBASE and the delete activated is working fine too. Could it be possible that an error while trying to delete a meta series in HBASE that doesn't exists anymore could lead to those shutdowns?
With the Warp10 version 2.5 I do have all those 5 metrics but as this event is occurring at directory reboot, the value recorded was zero or no values.

**Comment by hbs** [comment] 2021-02-11 16:03
Did you get a chance to try out 2.7.x?

**Comment by hbs** [comment] 2021-02-23 06:56
Closing this issue as it seems more of an operational issue than an intrinsic one. You can always re-open it later if need be.

**Closed by hbs** 2021-02-23 06:56 UTC
