### ISSUE TITLE
SETATTRIBUTES strange behaviour

### ISSUE THREAD

**Issue by miton18** [senx/warp10-platform#527] opened 2019-08-02 12:22 UTC
In WarpScript, it's possible to `RELABEL` a GTS with a `NULL` value, this action drop the label from the GTS.

It seems not possible to do the same thing with `SETATTRIBUTES`, is it an expected behaviour ?

[Quantum example](http://quantum.metrics.ovh.net/#/warpscript/TkVXR1RTIHsgJ2F0dHInICd2YWx1ZScgfSBSRUxBQkVMCgogICAgeyAnYXR0cicgTlVMTCB9IFJFTEFCRUwgLy8gV09SS1MsIGl0J3MgZHJvcCAiYXR0ciIgbGFiZWwKICAgIApORVdHVFMgeyAnYXR0cicgJ3ZhbHVlJyB9IFNFVEFUVFJJQlVURVMKCiAgICB7ICdhdHRyJyBOVUxMIH0gU0VUQVRUUklCVVRFUyAvLyBGQUlM/eyJ1cmwiOiJodHRwczovL3dhcnAxMC5ncmExLm1ldHJpY3Mub3ZoLm5ldC9hcGkvdjAiLCJmZXRjaEVuZHBvaW50IjoiL2ZldGNoIiwiaGVhZGVyTmFtZSI6IlgtV2FycDEwIn0%3D)

**Comment by hbs** [comment] 2019-08-02 12:30
Attributes are only set as a whole so yes this is the expected behavior

**Comment by miton18** [comment] 2019-08-02 14:09
Sorry, don't understand...
In a GTS instance, on an WarpScript context:
- to drop a label, I can use `{ 'attr' '' } RELABEL`
- to drop an attribute, I can use `{ 'attr' '' } SETATTRIBUTES`
- to drop a label, I can also use `{ 'attr' NULL } RELABEL`
- to drop an attribute, I can't use `{ 'attr' NULL } SETATTRIBUTES`

Even if the data structure for Attributes and Labels are differents, Why `SETATTRIBUTES` function cannot handle NULL value as empty string one ?

**Comment by hbs** [comment] 2019-08-02 20:35
The NULL value was incorrectly rejected due to a misplaced check.

You should have received an exception saying arguments were not STRING.

Fixed now, thanks for the catch.

**Closed** 2019-08-02 20:36 UTC

**Comment by miton18** [comment] 2019-08-05 12:50
Thx @hbs :-)
